<?php

include_once('openpublic_projects.features.inc');

/**
 * Implementation of hook_views_api().
 */
function openpublic_projects_views_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'openpublic_projects')
  );
}

function openpublic_projects_init() {
  drupal_add_css(drupal_get_path("module", 'openpublic_projects') . '/theme/openpublic_projects.css', 'file');
}

